name: GitHub Actions Demo
run-name: ${{ github.actor }} estÃ¡ probando 'Acciones de GitHub' ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ El trabajo se activÃ³ automÃ¡ticamente mediante un evento ${{ github.event_name }}."
      - run: echo "ğŸ§ Â¡Este trabajo ahora se estÃ¡ ejecutando en un servidor ${{ runner.os }} alojado por GitHub!"
      - run: echo "ğŸ” El nombre de tu rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}."
      - name: Consulte el codigo del repositorio
        uses: actions/checkout@v5
      - run: echo "ğŸ’¡ El repositorio ${{ github.repository }} El repositorio ha sido clonado al ejecutor."
      - run: echo "ğŸ–¥ï¸ El flujo de trabajo ahora estÃ¡ listo para probar su cÃ³digo en el ejecutor."
      - name: Lista todos los ficheros en el repositorio
        run: |
          ls -R ${{ github.workspace }}
      - run: echo "ğŸ El estado de este trabajo es ${{ job.status }}."
